name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Build binary
        run: |
          go build -v .
      - name: Setup docker
        uses: docker/setup-buildx-action@v2
      - name: Setup kind cluster
        run: |
          go install sigs.k8s.io/kind@v0.20.0
          kind create cluster --wait 5m
      - name: Create topology
        run: |
          ./ktm -topo testdata/client-server.yaml
      - name: Check topology
        run: |
          docker exec kind-control-plane kubectl wait --for=condition=Ready pods -n client-server --all
          docker exec kind-control-plane kubectl get pods -A
      - name: Cleanup
        run: |
          ./ktm -cleanup
